name: publish pre-releases as beta to npmjs
on:
  release:
    types: [prereleased]

jobs:
  publish-as-beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # node-version: 22.x
          # there's an issue with npm ci + npm 10.8.2 + node 22.5.0, so 
          # temporarily pinning to 22.4.x - see https://github.com/npm/cli/issues/7657
          node-version: 22.4.x
          registry-url: https://registry.npmjs.org
      - run: npm clean-install
      - run: npm publish --provenance --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
